In [9]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

In [4]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')
smile_cascade = cv2.CascadeClassifier('haarcascade_smile.xml')

In [ ]:
img = cv2.imread('ankitanarula.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray, 1.1, 5)

for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    smiles = smile_cascade.detectMultiScale(roi_color)
    for (ex,ey,ew,eh) in eyes:
         cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
    
    for (sx,sy,sw,sh) in smiles:
         cv2.rectangle(roi_color,(sx,sy),(sx+sw,sy+sh),(255,0,255),2)

cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
img = cv2.imread('Image.png')
faceCascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

#image = cv2.imread('Image.png')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Detect faces in the image
faces = faceCascade.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=5,
    
)

print "Found {0} faces!".format(len(faces))

# Draw a rectangle around the faces
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
    #cv2.imshow("Adding faces to traning set...", img[y: y + h, x: x + w])

cv2.imshow("Faces found", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Found 4 faces!


In [19]:
path = './im1/Images'
image_paths = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.jpg')]
#print image_path
# images will contains face images
images = []
# labels will contains the label that is assigned to the image
labels = []
for image_path in image_paths:
    # Read the image and convert to grayscale
    image_pil = Image.open(image_path).convert('L')
    # Convert the image format into numpy array
    image = np.array(image_pil, 'uint8')
    # Get the label of the image
    #nbr = int(os.path.split(image_path)[1].split(".")[0].replace("subject", ""))
    # Detect the face in the image
    faces = faceCascade.detectMultiScale(image)
    # If face is detected, append the face to images and the label to labels
    for (x, y, w, h) in faces:
        images.append(image[y: y + h, x: x + w])
        #labels.append(nbr)
        cv2.imshow("Adding faces to traning set...", image[y: y + h, x: x + w])
        cv2.waitKey(50)
cv2.destroyAllWindows()

In [20]:
images

[array([[29, 29, 29, ..., 42, 42, 42],
        [29, 29, 29, ..., 42, 42, 42],
        [29, 29, 29, ..., 42, 42, 42],
        ..., 
        [45, 40, 41, ..., 45, 45, 46],
        [44, 39, 40, ..., 45, 45, 46],
        [30, 37, 40, ..., 47, 47, 47]], dtype=uint8),
 array([[ 44,  48,  48, ...,  57,  51,  48],
        [ 47,  51,  51, ...,  55,  51,  50],
        [ 48,  49,  48, ...,  59,  56,  53],
        ..., 
        [102, 114, 142, ...,  28,  31,  32],
        [ 88, 107, 139, ...,  30,  33,  34],
        [ 64,  82, 113, ...,  30,  30,  31]], dtype=uint8),
 array([[172, 170, 165, ...,  53,  77,  81],
        [174, 171, 166, ...,  43,  62,  71],
        [170, 170, 168, ...,  38,  49,  62],
        ..., 
        [ 38,  45,  41, ...,  37,  37,  36],
        [ 43,  42,  42, ...,  38,  38,  37],
        [ 47,  38,  42, ...,  37,  39,  38]], dtype=uint8),
 array([[ 33,  71, 139, ...,  50,  51,  40],
        [ 40,  88, 143, ...,  46,  50,  43],
        [ 66,  97, 131, ...,  46,  49,  46],
    

In [1]:
from PIL import Image, ImageFilter
#Read image
im = Image.open( 'ankitanarula.jpg' )
#Display image
im.show()

#Applying a filter to the image
im_sharp = im.filter( ImageFilter.SHARPEN )
#Saving the filtered image to a new file
im_sharp.save( 'image_sharpened.jpg', 'JPEG' )

#Splitting the image into its respective bands, i.e. Red, Green,
#and Blue for RGB
r,g,b = im_sharp.split()

#Viewing EXIF data embedded in image
exif_data = im._getexif()
exif_data

In [ ]:
from PIL import Image
import glob, os

size = 128, 128

for infile in glob.glob("*.jpg"):
    file, ext = os.path.splitext(infile)
    im = Image.open(infile)
    im.thumbnail(size, Image.ANTIALIAS)
    im.save(file + ".thumbnail", "JPEG")